type SeedCategory = {
  name: string;
  slug: string;
  description: string;
  displayOrder: number;
  children?: SeedCategory[];
};

type SeedProductImage = {
  url: string;
  altText: string;
  width: number;
  height: number;
  sortOrder: number;
  isPrimary?: boolean;
};

type SeedVariant = {
  name: string;
  sku: string;
  material: string;
  color: string;
  size: string;
  priceCents: number;
  compareAtPriceCents?: number;
  stockQuantity: number;
  isDefault?: boolean;
};

type SeedProduct = {
  name: string;
  slug: string;
  sku: string;
  categorySlug: string;
  shortDescription: string;
  description: string;
  material: string;
  color: string;
  size: string;
  priceCents: number;
  compareAtPriceCents?: number;
  stockQuantity: number;
  isFeatured?: boolean;
  images: SeedProductImage[];
  variants: SeedVariant[];
};

export const seedCategories: SeedCategory[] = [
  {
    name: "Furniture",
    slug: "furniture",
    description: "Core furniture categories for the North Atelier catalog.",
    displayOrder: 1,
    children: [
      {
        name: "Sofas",
        slug: "sofas",
        description: "Tailored seating, sectionals, and statement sofas.",
        displayOrder: 1,
      },
      {
        name: "Chairs",
        slug: "chairs",
        description: "Dining chairs, lounge chairs, and occasional seating.",
        displayOrder: 2,
      },
      {
        name: "Tables",
        slug: "tables",
        description: "Dining, coffee, side, and console tables.",
        displayOrder: 3,
      },
      {
        name: "Beds",
        slug: "beds",
        description: "Platform beds, upholstered frames, and storage beds.",
        displayOrder: 4,
      },
      {
        name: "Wardrobes",
        slug: "wardrobes",
        description: "Bedroom storage with hanging space, drawers, and shelving.",
        displayOrder: 5,
      },
    ],
  },
];

export const seedProducts: SeedProduct[] = [
  {
    name: "Harbor Modular Sofa",
    slug: "harbor-modular-sofa",
    sku: "SOFA-HARBOR",
    categorySlug: "sofas",
    shortDescription: "Low-profile modular sofa with deep, relaxed seating.",
    description:
      "The Harbor Modular Sofa is built for layered living rooms and long evenings at home. Its broad seat depth, tailored seams, and refined base create a premium silhouette that still feels approachable and comfortable.",
    material: "Kiln-dried hardwood, high-resilience foam, linen weave upholstery",
    color: "Sand",
    size: "3-Seater",
    priceCents: 329900,
    compareAtPriceCents: 359900,
    stockQuantity: 9,
    isFeatured: true,
    images: [
      {
        url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=80",
        altText: "Harbor Modular Sofa in a warm living room",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
      {
        url: "https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=1400&q=80",
        altText: "Close detail of Harbor sofa upholstery",
        width: 1400,
        height: 1000,
        sortOrder: 2,
      },
    ],
    variants: [
      {
        name: "Sand / 3-Seater",
        sku: "SOFA-HARBOR-SAND-3",
        material: "Linen weave upholstery",
        color: "Sand",
        size: "3-Seater",
        priceCents: 329900,
        compareAtPriceCents: 359900,
        stockQuantity: 4,
        isDefault: true,
      },
      {
        name: "Olive / 3-Seater",
        sku: "SOFA-HARBOR-OLIVE-3",
        material: "Performance weave upholstery",
        color: "Olive",
        size: "3-Seater",
        priceCents: 339900,
        stockQuantity: 3,
      },
      {
        name: "Sand / Corner Sectional",
        sku: "SOFA-HARBOR-SAND-CORNER",
        material: "Linen weave upholstery",
        color: "Sand",
        size: "Corner Sectional",
        priceCents: 459900,
        stockQuantity: 2,
      },
    ],
  },
  {
    name: "Aster Curved Sofa",
    slug: "aster-curved-sofa",
    sku: "SOFA-ASTER",
    categorySlug: "sofas",
    shortDescription: "Curved statement sofa designed for open-plan rooms.",
    description:
      "The Aster Curved Sofa softens angular interiors with a sweeping profile and plush back support. It is intended as a central piece for spacious living rooms, hospitality lounges, and design-led apartments.",
    material: "Plywood frame, webbing suspension, boucle upholstery",
    color: "Ivory",
    size: "4-Seater",
    priceCents: 389900,
    compareAtPriceCents: 419900,
    stockQuantity: 5,
    isFeatured: true,
    images: [
      {
        url: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1400&q=80",
        altText: "Aster Curved Sofa in a contemporary interior",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Ivory / 4-Seater",
        sku: "SOFA-ASTER-IVORY-4",
        material: "Boucle upholstery",
        color: "Ivory",
        size: "4-Seater",
        priceCents: 389900,
        compareAtPriceCents: 419900,
        stockQuantity: 2,
        isDefault: true,
      },
      {
        name: "Stone / 4-Seater",
        sku: "SOFA-ASTER-STONE-4",
        material: "Textured chenille upholstery",
        color: "Stone",
        size: "4-Seater",
        priceCents: 394900,
        stockQuantity: 3,
      },
    ],
  },
  {
    name: "Marlowe Slipcover Sofa",
    slug: "marlowe-slipcover-sofa",
    sku: "SOFA-MARLOWE",
    categorySlug: "sofas",
    shortDescription: "Relaxed slipcovered sofa with generous sink-in comfort.",
    description:
      "The Marlowe Slipcover Sofa balances casual ease with premium finishing. It is tailored for family rooms and airy interiors where a softened silhouette and washable cover option matter as much as comfort.",
    material: "Hardwood frame, feather-wrap cushions, cotton-linen slipcover",
    color: "Oatmeal",
    size: "3-Seater",
    priceCents: 279900,
    stockQuantity: 12,
    images: [
      {
        url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1400&q=80",
        altText: "Marlowe Slipcover Sofa in a bright room",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Oatmeal / 3-Seater",
        sku: "SOFA-MARLOWE-OAT-3",
        material: "Cotton-linen slipcover",
        color: "Oatmeal",
        size: "3-Seater",
        priceCents: 279900,
        stockQuantity: 7,
        isDefault: true,
      },
      {
        name: "Fog / 2-Seater",
        sku: "SOFA-MARLOWE-FOG-2",
        material: "Cotton-linen slipcover",
        color: "Fog",
        size: "2-Seater",
        priceCents: 239900,
        stockQuantity: 5,
      },
    ],
  },
  {
    name: "Rowan Sectional Sofa",
    slug: "rowan-sectional-sofa",
    sku: "SOFA-ROWAN",
    categorySlug: "sofas",
    shortDescription: "Structured sectional with chaise for larger family spaces.",
    description:
      "The Rowan Sectional Sofa offers a firmer sit, clean arms, and a well-defined chaise. It suits contemporary homes that need clear geometry, substantial seating capacity, and durable upholstery.",
    material: "Solid pine frame, sinuous springs, performance fabric",
    color: "Graphite",
    size: "Left Chaise Sectional",
    priceCents: 419900,
    compareAtPriceCents: 449900,
    stockQuantity: 4,
    images: [
      {
        url: "https://images.unsplash.com/photo-1491924778227-f225b115b7a8?auto=format&fit=crop&w=1400&q=80",
        altText: "Rowan Sectional Sofa styled in a loft interior",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Graphite / Left Chaise",
        sku: "SOFA-ROWAN-GRAPHITE-L",
        material: "Performance fabric",
        color: "Graphite",
        size: "Left Chaise Sectional",
        priceCents: 419900,
        compareAtPriceCents: 449900,
        stockQuantity: 2,
        isDefault: true,
      },
      {
        name: "Taupe / Right Chaise",
        sku: "SOFA-ROWAN-TAUPE-R",
        material: "Performance fabric",
        color: "Taupe",
        size: "Right Chaise Sectional",
        priceCents: 419900,
        stockQuantity: 2,
      },
    ],
  },
  {
    name: "Atelier Lounge Chair",
    slug: "atelier-lounge-chair",
    sku: "CHAIR-ATELIER",
    categorySlug: "chairs",
    shortDescription: "Sculpted lounge chair with a compact footprint.",
    description:
      "The Atelier Lounge Chair combines a curved backrest, visible timber frame, and tactile upholstery. It works in living rooms, bedrooms, and hospitality spaces where accent seating should feel distinct but not oversized.",
    material: "Solid ash, webbing support, boucle upholstery",
    color: "Ivory",
    size: "Single Seat",
    priceCents: 119900,
    stockQuantity: 18,
    images: [
      {
        url: "https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&w=1400&q=80",
        altText: "Atelier Lounge Chair in an editorial corner",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Ivory / Ash",
        sku: "CHAIR-ATELIER-IVORY-ASH",
        material: "Boucle upholstery, ash frame",
        color: "Ivory",
        size: "Single Seat",
        priceCents: 119900,
        stockQuantity: 10,
        isDefault: true,
      },
      {
        name: "Charcoal / Walnut",
        sku: "CHAIR-ATELIER-CHARCOAL-WALNUT",
        material: "Textured weave upholstery, walnut frame",
        color: "Charcoal",
        size: "Single Seat",
        priceCents: 124900,
        stockQuantity: 8,
      },
    ],
  },
  {
    name: "Linden Dining Chair",
    slug: "linden-dining-chair",
    sku: "CHAIR-LINDEN",
    categorySlug: "chairs",
    shortDescription: "Upholstered dining chair with a softly curved back.",
    description:
      "The Linden Dining Chair is proportioned for long meals and everyday comfort. Its wraparound back, tapered legs, and tactile upholstery make it suitable for both residential dining rooms and boutique hospitality projects.",
    material: "Solid oak, molded backrest, linen blend upholstery",
    color: "Pebble",
    size: "Dining Chair",
    priceCents: 45900,
    stockQuantity: 30,
    images: [
      {
        url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=80",
        altText: "Linden Dining Chair beside a dining table",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Pebble / Oak",
        sku: "CHAIR-LINDEN-PEBBLE-OAK",
        material: "Linen blend upholstery, oak frame",
        color: "Pebble",
        size: "Dining Chair",
        priceCents: 45900,
        stockQuantity: 16,
        isDefault: true,
      },
      {
        name: "Olive / Walnut",
        sku: "CHAIR-LINDEN-OLIVE-WALNUT",
        material: "Textured weave upholstery, walnut frame",
        color: "Olive",
        size: "Dining Chair",
        priceCents: 48900,
        stockQuantity: 14,
      },
    ],
  },
  {
    name: "Tide Counter Stool",
    slug: "tide-counter-stool",
    sku: "CHAIR-TIDE",
    categorySlug: "chairs",
    shortDescription: "Counter stool with curved timber back and upholstered seat.",
    description:
      "The Tide Counter Stool is designed for kitchen islands and casual dining spaces. Its supportive backrest and padded seat make it more comfortable than a minimal bar stool while preserving a clean visual profile.",
    material: "Solid oak, steel footrest, performance fabric seat",
    color: "Mushroom",
    size: "Counter Height",
    priceCents: 69900,
    stockQuantity: 20,
    images: [
      {
        url: "https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&w=1400&q=80",
        altText: "Tide Counter Stool at a kitchen island",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Mushroom / Counter Height",
        sku: "CHAIR-TIDE-MUSHROOM-COUNTER",
        material: "Performance fabric seat, oak frame",
        color: "Mushroom",
        size: "Counter Height",
        priceCents: 69900,
        stockQuantity: 12,
        isDefault: true,
      },
      {
        name: "Ink / Bar Height",
        sku: "CHAIR-TIDE-INK-BAR",
        material: "Performance fabric seat, smoked oak frame",
        color: "Ink",
        size: "Bar Height",
        priceCents: 74900,
        stockQuantity: 8,
      },
    ],
  },
  {
    name: "North Reading Chair",
    slug: "north-reading-chair",
    sku: "CHAIR-NORTH",
    categorySlug: "chairs",
    shortDescription: "Relaxed reading chair with broad arms and deep seat.",
    description:
      "The North Reading Chair is meant for corners dedicated to books, music, and quiet time. A deep seat and broad upholstered arms make it exceptionally comfortable without feeling oversized in smaller rooms.",
    material: "Hardwood frame, feather-wrap cushion, brushed cotton upholstery",
    color: "Camel",
    size: "Single Seat",
    priceCents: 134900,
    stockQuantity: 11,
    images: [
      {
        url: "https://images.unsplash.com/photo-1549187774-b4e9b0445b41?auto=format&fit=crop&w=1400&q=80",
        altText: "North Reading Chair next to a floor lamp",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Camel / Oak Base",
        sku: "CHAIR-NORTH-CAMEL-OAK",
        material: "Brushed cotton upholstery, oak base",
        color: "Camel",
        size: "Single Seat",
        priceCents: 134900,
        stockQuantity: 6,
        isDefault: true,
      },
      {
        name: "Forest / Walnut Base",
        sku: "CHAIR-NORTH-FOREST-WALNUT",
        material: "Brushed cotton upholstery, walnut base",
        color: "Forest",
        size: "Single Seat",
        priceCents: 139900,
        stockQuantity: 5,
      },
    ],
  },
  {
    name: "Cascade Dining Table",
    slug: "cascade-dining-table",
    sku: "TABLE-CASCADE",
    categorySlug: "tables",
    shortDescription: "Large-format dining table with architectural base.",
    description:
      "The Cascade Dining Table is designed for generous gatherings and visual presence. A substantial tabletop and sculptural pedestal base create a centerpiece that feels refined while remaining practical for daily use.",
    material: "Travertine veneer, engineered core, solid oak base",
    color: "Natural Stone",
    size: "240 cm",
    priceCents: 419900,
    compareAtPriceCents: 449900,
    stockQuantity: 6,
    isFeatured: true,
    images: [
      {
        url: "https://images.unsplash.com/photo-1505409628601-edc9af17fda6?auto=format&fit=crop&w=1400&q=80",
        altText: "Cascade Dining Table in a modern dining room",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Natural Stone / 240 cm",
        sku: "TABLE-CASCADE-STONE-240",
        material: "Travertine veneer, oak base",
        color: "Natural Stone",
        size: "240 cm",
        priceCents: 419900,
        compareAtPriceCents: 449900,
        stockQuantity: 3,
        isDefault: true,
      },
      {
        name: "Smoked Oak / 220 cm",
        sku: "TABLE-CASCADE-OAK-220",
        material: "Smoked oak veneer, oak base",
        color: "Smoked Oak",
        size: "220 cm",
        priceCents: 389900,
        stockQuantity: 3,
      },
    ],
  },
  {
    name: "Vale Coffee Table",
    slug: "vale-coffee-table",
    sku: "TABLE-VALE",
    categorySlug: "tables",
    shortDescription: "Rounded coffee table with stone top and timber base.",
    description:
      "The Vale Coffee Table blends sculptural softness with durable construction. Its rounded top and solid base create a grounded focal point suited to modern living rooms and hospitality lounges.",
    material: "Marble top, solid ash base",
    color: "Warm White",
    size: "110 cm",
    priceCents: 129900,
    stockQuantity: 14,
    images: [
      {
        url: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1400&q=80",
        altText: "Vale Coffee Table in a minimalist lounge",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Warm White / 110 cm",
        sku: "TABLE-VALE-WHITE-110",
        material: "Marble top, ash base",
        color: "Warm White",
        size: "110 cm",
        priceCents: 129900,
        stockQuantity: 7,
        isDefault: true,
      },
      {
        name: "Black Marble / 90 cm",
        sku: "TABLE-VALE-BLACK-90",
        material: "Black marble top, walnut base",
        color: "Black Marble",
        size: "90 cm",
        priceCents: 124900,
        stockQuantity: 7,
      },
    ],
  },
  {
    name: "Sable Side Table",
    slug: "sable-side-table",
    sku: "TABLE-SABLE",
    categorySlug: "tables",
    shortDescription: "Compact side table for bedrooms and seating zones.",
    description:
      "The Sable Side Table is a versatile accent piece for next-to-sofa and bedside placement. Its compact footprint, rich veneer, and subtle edge profile make it easy to use across multiple interior styles.",
    material: "Walnut veneer, engineered wood core",
    color: "Walnut",
    size: "45 cm",
    priceCents: 32900,
    stockQuantity: 28,
    images: [
      {
        url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1400&q=80",
        altText: "Sable Side Table in a living room",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Walnut / 45 cm",
        sku: "TABLE-SABLE-WALNUT-45",
        material: "Walnut veneer",
        color: "Walnut",
        size: "45 cm",
        priceCents: 32900,
        stockQuantity: 14,
        isDefault: true,
      },
      {
        name: "Black Oak / 45 cm",
        sku: "TABLE-SABLE-BLACK-45",
        material: "Black oak veneer",
        color: "Black Oak",
        size: "45 cm",
        priceCents: 33900,
        stockQuantity: 14,
      },
    ],
  },
  {
    name: "Mira Console Table",
    slug: "mira-console-table",
    sku: "TABLE-MIRA",
    categorySlug: "tables",
    shortDescription: "Slim console table for entryways and transitional spaces.",
    description:
      "The Mira Console Table is designed for narrow hallways and entry zones that still need a sense of polish. A slim profile, floating shelf, and warm finish make it practical without appearing visually heavy.",
    material: "Oak veneer, powder-coated steel",
    color: "Natural Oak",
    size: "140 cm",
    priceCents: 87900,
    stockQuantity: 10,
    images: [
      {
        url: "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1400&q=80",
        altText: "Mira Console Table in an entryway",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Natural Oak / 140 cm",
        sku: "TABLE-MIRA-OAK-140",
        material: "Oak veneer, steel frame",
        color: "Natural Oak",
        size: "140 cm",
        priceCents: 87900,
        stockQuantity: 5,
        isDefault: true,
      },
      {
        name: "Smoked Oak / 160 cm",
        sku: "TABLE-MIRA-SMOKED-160",
        material: "Smoked oak veneer, steel frame",
        color: "Smoked Oak",
        size: "160 cm",
        priceCents: 95900,
        stockQuantity: 5,
      },
    ],
  },
  {
    name: "Mora Storage Bed",
    slug: "mora-storage-bed",
    sku: "BED-MORA",
    categorySlug: "beds",
    shortDescription: "Platform bed with integrated under-frame storage.",
    description:
      "The Mora Storage Bed combines upholstered softness with concealed storage capacity, making it ideal for city bedrooms where space is precious. Its proportions feel calm and architectural, with subtle detailing around the base.",
    material: "Solid pine, engineered panels, woven upholstery",
    color: "Mist",
    size: "Queen",
    priceCents: 279900,
    stockQuantity: 11,
    isFeatured: true,
    images: [
      {
        url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=80",
        altText: "Mora Storage Bed in a serene bedroom",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Mist / Queen",
        sku: "BED-MORA-MIST-QUEEN",
        material: "Woven upholstery",
        color: "Mist",
        size: "Queen",
        priceCents: 279900,
        stockQuantity: 6,
        isDefault: true,
      },
      {
        name: "Graphite / King",
        sku: "BED-MORA-GRAPHITE-KING",
        material: "Performance weave upholstery",
        color: "Graphite",
        size: "King",
        priceCents: 309900,
        stockQuantity: 5,
      },
    ],
  },
  {
    name: "Soma Upholstered Bed",
    slug: "soma-upholstered-bed",
    sku: "BED-SOMA",
    categorySlug: "beds",
    shortDescription: "Softly padded bed with tailored channel headboard.",
    description:
      "The Soma Upholstered Bed brings hotel-like softness into residential bedrooms. Its gently channeled headboard and low platform proportion create a refined look that still feels calm and easy to style.",
    material: "Hardwood frame, foam padding, chenille upholstery",
    color: "Cloud",
    size: "King",
    priceCents: 319900,
    compareAtPriceCents: 349900,
    stockQuantity: 7,
    images: [
      {
        url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=80",
        altText: "Soma Upholstered Bed in a neutral bedroom",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Cloud / King",
        sku: "BED-SOMA-CLOUD-KING",
        material: "Chenille upholstery",
        color: "Cloud",
        size: "King",
        priceCents: 319900,
        compareAtPriceCents: 349900,
        stockQuantity: 3,
        isDefault: true,
      },
      {
        name: "Dune / Queen",
        sku: "BED-SOMA-DUNE-QUEEN",
        material: "Chenille upholstery",
        color: "Dune",
        size: "Queen",
        priceCents: 289900,
        stockQuantity: 4,
      },
    ],
  },
  {
    name: "Orion Platform Bed",
    slug: "orion-platform-bed",
    sku: "BED-ORION",
    categorySlug: "beds",
    shortDescription: "Timber platform bed with wide rail detail.",
    description:
      "The Orion Platform Bed is designed for customers who prefer visible wood grain and a more architectural frame. Its broad rails, recessed legs, and quiet detailing bring a refined presence to the room.",
    material: "Solid oak, oak veneer slats",
    color: "Natural Oak",
    size: "Queen",
    priceCents: 239900,
    stockQuantity: 9,
    images: [
      {
        url: "https://images.unsplash.com/photo-1505693536928-8d95be1ad1be?auto=format&fit=crop&w=1400&q=80",
        altText: "Orion Platform Bed with crisp bedding",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Natural Oak / Queen",
        sku: "BED-ORION-OAK-QUEEN",
        material: "Solid oak",
        color: "Natural Oak",
        size: "Queen",
        priceCents: 239900,
        stockQuantity: 5,
        isDefault: true,
      },
      {
        name: "Smoked Oak / King",
        sku: "BED-ORION-SMOKED-KING",
        material: "Smoked oak",
        color: "Smoked Oak",
        size: "King",
        priceCents: 269900,
        stockQuantity: 4,
      },
    ],
  },
  {
    name: "Arden Canopy Bed",
    slug: "arden-canopy-bed",
    sku: "BED-ARDEN",
    categorySlug: "beds",
    shortDescription: "Minimal canopy bed with slender metal frame.",
    description:
      "The Arden Canopy Bed creates a dramatic bedroom focal point without visual heaviness. Its slim frame and upholstered headboard pair well with modern, transitional, and boutique hospitality-inspired interiors.",
    material: "Powder-coated steel, padded upholstered headboard",
    color: "Matte Black",
    size: "King",
    priceCents: 349900,
    stockQuantity: 5,
    images: [
      {
        url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=80",
        altText: "Arden Canopy Bed in a dramatic bedroom",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Matte Black / King",
        sku: "BED-ARDEN-BLACK-KING",
        material: "Powder-coated steel, upholstered headboard",
        color: "Matte Black",
        size: "King",
        priceCents: 349900,
        stockQuantity: 2,
        isDefault: true,
      },
      {
        name: "Bronze / Queen",
        sku: "BED-ARDEN-BRONZE-QUEEN",
        material: "Powder-coated steel, upholstered headboard",
        color: "Bronze",
        size: "Queen",
        priceCents: 329900,
        stockQuantity: 3,
      },
    ],
  },
  {
    name: "Cove Double Wardrobe",
    slug: "cove-double-wardrobe",
    sku: "WARDROBE-COVE",
    categorySlug: "wardrobes",
    shortDescription: "Two-door wardrobe with drawers and adjustable shelves.",
    description:
      "The Cove Double Wardrobe is designed for modern bedrooms that need generous storage without the visual bulk of built-ins. A balanced internal layout provides hanging space, drawers, and shelving for daily organization.",
    material: "Oak veneer, soft-close hinges, ash interior",
    color: "Natural Oak",
    size: "160 cm",
    priceCents: 259900,
    stockQuantity: 8,
    images: [
      {
        url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=80",
        altText: "Cove Double Wardrobe in a calm bedroom",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Natural Oak / 160 cm",
        sku: "WARDROBE-COVE-OAK-160",
        material: "Oak veneer",
        color: "Natural Oak",
        size: "160 cm",
        priceCents: 259900,
        stockQuantity: 4,
        isDefault: true,
      },
      {
        name: "Smoked Oak / 180 cm",
        sku: "WARDROBE-COVE-SMOKED-180",
        material: "Smoked oak veneer",
        color: "Smoked Oak",
        size: "180 cm",
        priceCents: 289900,
        stockQuantity: 4,
      },
    ],
  },
  {
    name: "Haven Sliding Wardrobe",
    slug: "haven-sliding-wardrobe",
    sku: "WARDROBE-HAVEN",
    categorySlug: "wardrobes",
    shortDescription: "Sliding-door wardrobe for compact bedrooms.",
    description:
      "The Haven Sliding Wardrobe is optimized for tighter floorplans where hinged doors are not ideal. Its clean front elevation, concealed runners, and mixed hanging-shelf interior make it highly practical for daily use.",
    material: "Melamine-faced oak veneer panels, aluminum track",
    color: "Sand Oak",
    size: "200 cm",
    priceCents: 299900,
    compareAtPriceCents: 329900,
    stockQuantity: 6,
    isFeatured: true,
    images: [
      {
        url: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1400&q=80",
        altText: "Haven Sliding Wardrobe in a compact bedroom",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Sand Oak / 200 cm",
        sku: "WARDROBE-HAVEN-SAND-200",
        material: "Oak veneer panels, aluminum track",
        color: "Sand Oak",
        size: "200 cm",
        priceCents: 299900,
        compareAtPriceCents: 329900,
        stockQuantity: 3,
        isDefault: true,
      },
      {
        name: "Clay Taupe / 220 cm",
        sku: "WARDROBE-HAVEN-CLAY-220",
        material: "Lacquered panels, aluminum track",
        color: "Clay Taupe",
        size: "220 cm",
        priceCents: 324900,
        stockQuantity: 3,
      },
    ],
  },
  {
    name: "Alder Three-Door Wardrobe",
    slug: "alder-three-door-wardrobe",
    sku: "WARDROBE-ALDER",
    categorySlug: "wardrobes",
    shortDescription: "Traditional wardrobe with modern detailing and deep storage.",
    description:
      "The Alder Three-Door Wardrobe offers a more classic proportion while keeping detailing restrained and contemporary. Inside, hanging rails, drawers, and upper shelving are arranged for practical full-season storage.",
    material: "Walnut veneer, solid timber pulls, birch drawers",
    color: "Walnut",
    size: "180 cm",
    priceCents: 319900,
    stockQuantity: 5,
    images: [
      {
        url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=80",
        altText: "Alder Three-Door Wardrobe in a warm bedroom",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Walnut / 180 cm",
        sku: "WARDROBE-ALDER-WALNUT-180",
        material: "Walnut veneer",
        color: "Walnut",
        size: "180 cm",
        priceCents: 319900,
        stockQuantity: 2,
        isDefault: true,
      },
      {
        name: "Natural Oak / 180 cm",
        sku: "WARDROBE-ALDER-OAK-180",
        material: "Oak veneer",
        color: "Natural Oak",
        size: "180 cm",
        priceCents: 309900,
        stockQuantity: 3,
      },
    ],
  },
  {
    name: "Ledger Linen Wardrobe",
    slug: "ledger-linen-wardrobe",
    sku: "WARDROBE-LEDGER",
    categorySlug: "wardrobes",
    shortDescription: "Tall wardrobe with fabric-front detail and soft-close drawers.",
    description:
      "The Ledger Linen Wardrobe brings a softer material expression into bedroom storage through subtle fabric-front detailing. It is designed for customers who want their storage pieces to feel integrated with upholstered bedroom furniture.",
    material: "Oak veneer, linen panel insets, soft-close hardware",
    color: "Putty",
    size: "170 cm",
    priceCents: 284900,
    stockQuantity: 7,
    images: [
      {
        url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=80",
        altText: "Ledger Linen Wardrobe styled in a textured bedroom",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Putty / 170 cm",
        sku: "WARDROBE-LEDGER-PUTTY-170",
        material: "Oak veneer, linen insets",
        color: "Putty",
        size: "170 cm",
        priceCents: 284900,
        stockQuantity: 4,
        isDefault: true,
      },
      {
        name: "Graphite / 170 cm",
        sku: "WARDROBE-LEDGER-GRAPHITE-170",
        material: "Oak veneer, woven panel insets",
        color: "Graphite",
        size: "170 cm",
        priceCents: 289900,
        stockQuantity: 3,
      },
    ],
  },
  {
    name: "Briar Corner Sofa",
    slug: "briar-corner-sofa",
    sku: "SOFA-BRIAR",
    categorySlug: "sofas",
    shortDescription: "Contemporary corner sofa with soft lines and deep cushions.",
    description:
      "The Briar Corner Sofa is designed for larger living rooms that need an inviting centerpiece. It combines rounded lines, generous seat depth, and refined upholstery for a lounge-forward profile that still feels polished.",
    material: "Birch frame, zig-zag springs, textured performance upholstery",
    color: "Pebble",
    size: "Corner Sectional",
    priceCents: 449900,
    compareAtPriceCents: 479900,
    stockQuantity: 6,
    images: [
      {
        url: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1400&q=80",
        altText: "Briar Corner Sofa in a spacious living room",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Pebble / Corner Sectional",
        sku: "SOFA-BRIAR-PEBBLE-CORNER",
        material: "Textured performance upholstery",
        color: "Pebble",
        size: "Corner Sectional",
        priceCents: 449900,
        compareAtPriceCents: 479900,
        stockQuantity: 3,
        isDefault: true,
      },
      {
        name: "Sage / Corner Sectional",
        sku: "SOFA-BRIAR-SAGE-CORNER",
        material: "Textured performance upholstery",
        color: "Sage",
        size: "Corner Sectional",
        priceCents: 454900,
        stockQuantity: 3,
      },
    ],
  },
  {
    name: "Edison Recline Chair",
    slug: "edison-recline-chair",
    sku: "CHAIR-EDISON",
    categorySlug: "chairs",
    shortDescription: "Modern recline chair with hidden footrest and supportive back.",
    description:
      "The Edison Recline Chair brings discreet comfort into contemporary interiors. Its tailored silhouette hides a smooth recline mechanism, making it ideal for media rooms, reading corners, and relaxed living spaces.",
    material: "Steel mechanism, hardwood frame, leather upholstery",
    color: "Cognac",
    size: "Single Seat",
    priceCents: 164900,
    stockQuantity: 9,
    images: [
      {
        url: "https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&w=1400&q=80",
        altText: "Edison Recline Chair with warm leather upholstery",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Cognac / Leather",
        sku: "CHAIR-EDISON-COGNAC-LEATHER",
        material: "Leather upholstery",
        color: "Cognac",
        size: "Single Seat",
        priceCents: 164900,
        stockQuantity: 5,
        isDefault: true,
      },
      {
        name: "Graphite / Performance Fabric",
        sku: "CHAIR-EDISON-GRAPHITE-FABRIC",
        material: "Performance fabric upholstery",
        color: "Graphite",
        size: "Single Seat",
        priceCents: 154900,
        stockQuantity: 4,
      },
    ],
  },
  {
    name: "Juniper Bench",
    slug: "juniper-bench",
    sku: "CHAIR-JUNIPER",
    categorySlug: "chairs",
    shortDescription: "Upholstered bench for dining tables, hallways, or bed ends.",
    description:
      "The Juniper Bench is a flexible accent piece designed to move between rooms with ease. Its slim profile, padded seat, and solid oak frame make it suited to entryways, dining setups, and bedroom styling.",
    material: "Solid oak, foam seat, woven upholstery",
    color: "Flax",
    size: "140 cm",
    priceCents: 89900,
    stockQuantity: 15,
    images: [
      {
        url: "https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&w=1400&q=80",
        altText: "Juniper Bench in a minimal hallway",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Flax / 140 cm",
        sku: "CHAIR-JUNIPER-FLAX-140",
        material: "Woven upholstery, oak frame",
        color: "Flax",
        size: "140 cm",
        priceCents: 89900,
        stockQuantity: 8,
        isDefault: true,
      },
      {
        name: "Charcoal / 160 cm",
        sku: "CHAIR-JUNIPER-CHARCOAL-160",
        material: "Textured upholstery, smoked oak frame",
        color: "Charcoal",
        size: "160 cm",
        priceCents: 97900,
        stockQuantity: 7,
      },
    ],
  },
  {
    name: "Palisade Extendable Table",
    slug: "palisade-extendable-table",
    sku: "TABLE-PALISADE",
    categorySlug: "tables",
    shortDescription: "Extendable dining table for everyday use and larger gatherings.",
    description:
      "The Palisade Extendable Table offers clean proportions for daily dining with an integrated extension system for guests. Its understated detailing and durable oak construction make it a reliable anchor for family homes.",
    material: "Solid oak, oak veneer extension leaves",
    color: "Natural Oak",
    size: "180-240 cm",
    priceCents: 239900,
    stockQuantity: 8,
    images: [
      {
        url: "https://images.unsplash.com/photo-1505409628601-edc9af17fda6?auto=format&fit=crop&w=1400&q=80",
        altText: "Palisade Extendable Table in a bright dining room",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Natural Oak / 180-240 cm",
        sku: "TABLE-PALISADE-OAK-180-240",
        material: "Solid oak",
        color: "Natural Oak",
        size: "180-240 cm",
        priceCents: 239900,
        stockQuantity: 4,
        isDefault: true,
      },
      {
        name: "Smoked Oak / 200-260 cm",
        sku: "TABLE-PALISADE-SMOKED-200-260",
        material: "Smoked oak",
        color: "Smoked Oak",
        size: "200-260 cm",
        priceCents: 259900,
        stockQuantity: 4,
      },
    ],
  },
  {
    name: "Halo Nesting Tables",
    slug: "halo-nesting-tables",
    sku: "TABLE-HALO",
    categorySlug: "tables",
    shortDescription: "Two-piece nesting tables with stone-look tops and metal base.",
    description:
      "The Halo Nesting Tables are designed for flexible living spaces where surfaces need to expand and contract easily. Their rounded silhouette and mixed-material finish add depth without visual clutter.",
    material: "Sintered stone tops, powder-coated steel base",
    color: "Ivory Stone",
    size: "Set of 2",
    priceCents: 109900,
    stockQuantity: 18,
    images: [
      {
        url: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=1400&q=80",
        altText: "Halo Nesting Tables layered in a lounge",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Ivory Stone / Set of 2",
        sku: "TABLE-HALO-IVORY-SET2",
        material: "Sintered stone, steel base",
        color: "Ivory Stone",
        size: "Set of 2",
        priceCents: 109900,
        stockQuantity: 9,
        isDefault: true,
      },
      {
        name: "Graphite Stone / Set of 2",
        sku: "TABLE-HALO-GRAPHITE-SET2",
        material: "Sintered stone, steel base",
        color: "Graphite Stone",
        size: "Set of 2",
        priceCents: 112900,
        stockQuantity: 9,
      },
    ],
  },
  {
    name: "Elowen Nightstand",
    slug: "elowen-nightstand",
    sku: "TABLE-ELOWEN",
    categorySlug: "tables",
    shortDescription: "Two-drawer bedside table with rounded corners and warm wood grain.",
    description:
      "The Elowen Nightstand is sized for contemporary bedrooms that need useful storage without heaviness. Rounded edges, soft-close drawers, and a rich veneer finish give it a calm, premium expression.",
    material: "Walnut veneer, birch drawer boxes, solid wood pulls",
    color: "Walnut",
    size: "55 cm",
    priceCents: 64900,
    stockQuantity: 22,
    images: [
      {
        url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1400&q=80",
        altText: "Elowen Nightstand beside an upholstered bed",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Walnut / 55 cm",
        sku: "TABLE-ELOWEN-WALNUT-55",
        material: "Walnut veneer",
        color: "Walnut",
        size: "55 cm",
        priceCents: 64900,
        stockQuantity: 11,
        isDefault: true,
      },
      {
        name: "Natural Oak / 55 cm",
        sku: "TABLE-ELOWEN-OAK-55",
        material: "Oak veneer",
        color: "Natural Oak",
        size: "55 cm",
        priceCents: 62900,
        stockQuantity: 11,
      },
    ],
  },
  {
    name: "Isla Panel Bed",
    slug: "isla-panel-bed",
    sku: "BED-ISLA",
    categorySlug: "beds",
    shortDescription: "Timber bed frame with upholstered inset headboard.",
    description:
      "The Isla Panel Bed pairs warm wood tones with a softly upholstered headboard for a layered bedroom look. It suits modern and transitional interiors that need a bed with presence but not bulk.",
    material: "Oak veneer, solid wood legs, textured upholstered headboard",
    color: "Oak and Sand",
    size: "Queen",
    priceCents: 259900,
    stockQuantity: 10,
    images: [
      {
        url: "https://images.unsplash.com/photo-1505693536928-8d95be1ad1be?auto=format&fit=crop&w=1400&q=80",
        altText: "Isla Panel Bed in a layered neutral bedroom",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Oak and Sand / Queen",
        sku: "BED-ISLA-OAK-SAND-QUEEN",
        material: "Oak veneer, upholstered headboard",
        color: "Oak and Sand",
        size: "Queen",
        priceCents: 259900,
        stockQuantity: 5,
        isDefault: true,
      },
      {
        name: "Oak and Stone / King",
        sku: "BED-ISLA-OAK-STONE-KING",
        material: "Oak veneer, upholstered headboard",
        color: "Oak and Stone",
        size: "King",
        priceCents: 289900,
        stockQuantity: 5,
      },
    ],
  },
  {
    name: "Meridian Storage Bed",
    slug: "meridian-storage-bed",
    sku: "BED-MERIDIAN",
    categorySlug: "beds",
    shortDescription: "Lift-up storage bed with padded frame and concealed compartments.",
    description:
      "The Meridian Storage Bed is built for bedrooms where every square meter matters. A smooth lift mechanism reveals generous internal storage while the exterior remains streamlined and quietly luxurious.",
    material: "Engineered frame, lift hardware, boucle upholstery",
    color: "Stone",
    size: "King",
    priceCents: 339900,
    stockQuantity: 6,
    images: [
      {
        url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=80",
        altText: "Meridian Storage Bed styled with layered bedding",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Stone / King",
        sku: "BED-MERIDIAN-STONE-KING",
        material: "Boucle upholstery",
        color: "Stone",
        size: "King",
        priceCents: 339900,
        stockQuantity: 3,
        isDefault: true,
      },
      {
        name: "Dune / Queen",
        sku: "BED-MERIDIAN-DUNE-QUEEN",
        material: "Textured weave upholstery",
        color: "Dune",
        size: "Queen",
        priceCents: 314900,
        stockQuantity: 3,
      },
    ],
  },
  {
    name: "Borough Wardrobe",
    slug: "borough-wardrobe",
    sku: "WARDROBE-BOROUGH",
    categorySlug: "wardrobes",
    shortDescription: "Compact two-door wardrobe with drawers for apartment bedrooms.",
    description:
      "The Borough Wardrobe is tailored for smaller homes where storage still needs to feel considered. Its interior combines hanging space and low drawers, while the exterior remains minimal and easy to style.",
    material: "Oak veneer, engineered panels, soft-close runners",
    color: "Clay Oak",
    size: "140 cm",
    priceCents: 219900,
    stockQuantity: 9,
    images: [
      {
        url: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1400&q=80",
        altText: "Borough Wardrobe in a compact bedroom",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Clay Oak / 140 cm",
        sku: "WARDROBE-BOROUGH-CLAY-140",
        material: "Oak veneer",
        color: "Clay Oak",
        size: "140 cm",
        priceCents: 219900,
        stockQuantity: 5,
        isDefault: true,
      },
      {
        name: "Mist Grey / 140 cm",
        sku: "WARDROBE-BOROUGH-MIST-140",
        material: "Painted veneer",
        color: "Mist Grey",
        size: "140 cm",
        priceCents: 224900,
        stockQuantity: 4,
      },
    ],
  },
  {
    name: "Monroe Mirror Wardrobe",
    slug: "monroe-mirror-wardrobe",
    sku: "WARDROBE-MONROE",
    categorySlug: "wardrobes",
    shortDescription: "Three-door wardrobe with integrated mirror panel and shelf storage.",
    description:
      "The Monroe Mirror Wardrobe adds function and light to the bedroom through a full-height mirrored door. Inside, a balanced arrangement of hanging rails and shelves supports both daily essentials and seasonal storage.",
    material: "Ash veneer, mirrored glass panel, soft-close hinges",
    color: "Pale Ash",
    size: "190 cm",
    priceCents: 334900,
    stockQuantity: 5,
    images: [
      {
        url: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=80",
        altText: "Monroe Mirror Wardrobe in a bright bedroom",
        width: 1400,
        height: 1000,
        sortOrder: 1,
        isPrimary: true,
      },
    ],
    variants: [
      {
        name: "Pale Ash / 190 cm",
        sku: "WARDROBE-MONROE-ASH-190",
        material: "Ash veneer, mirrored glass",
        color: "Pale Ash",
        size: "190 cm",
        priceCents: 334900,
        stockQuantity: 2,
        isDefault: true,
      },
      {
        name: "Walnut / 190 cm",
        sku: "WARDROBE-MONROE-WALNUT-190",
        material: "Walnut veneer, mirrored glass",
        color: "Walnut",
        size: "190 cm",
        priceCents: 344900,
        stockQuantity: 3,
      },
    ],
  },
];
